### ISSUE TITLE
Inconsistency on secretTUSD Balance

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#1]
I have a 50TUSD TX under transactions but can't see the secretTUSD in the bridge screen

![image](https://user-images.githubusercontent.com/15679491/100809346-ee26d280-3403-11eb-99f7-2e4a6ed3b6e9.png)
vs
![image](https://user-images.githubusercontent.com/15679491/100809364-f7b03a80-3403-11eb-9bf9-01e6becc3022.png)

**Comment by assafmo** [comment]
You sent 50 sTUSD to `...zwh`, the recipient wallet on this^ screenshot is `...qfn`. Try looking at the sTUSD balance of your `...zwh` wallet?

**Comment by cankisagun** [comment]
Gotcha - I found this different tiny error now with keplr extensiopn vs. UI
100 SETH on Keplr vs. 0.1 secretETH on GUI

![image](https://user-images.githubusercontent.com/15679491/100911656-845b0700-349d-11eb-9949-89c475d27be3.png)


![image](https://user-images.githubusercontent.com/15679491/100911631-7d33f900-349d-11eb-8175-7b38c9933999.png)

**Comment by assafmo** [comment]
Ohhhhh that's fully because of @Cashmaney, I'll let him explain. :stuck_out_tongue: 
The gist of it is that this is testnet behavior only.
