### ISSUE TITLE
Automate close tab after a TX is complete - low priority

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#11]
Once an bridge TX is completed, Alice needs to hit close on the left part of the screen before she can click anything else. Say Alice wants to click on SN -> ETH bridge, Alice won't be able to do that unless she clicks cancel first...

If we can automate the clicking on cancel by clicking any button on the UI that'd be nice but not worth a lot of effort

**Comment by assafmo** [comment]
Yeah that's a weird bug.
