### ISSUE TITLE
Improve "not enough gas" error

### ISSUE THREAD

**Issue by lauracw100** [scrtlabs/EthereumBridgeFrontend#117]
I was trying to provide liquidity for sSCRT/sUSDC pair and got this error in the UI.

![image](https://user-images.githubusercontent.com/436905/111884619-30ffbc80-8999-11eb-9f38-5a8ba4e3af42.png)

Looking at the explorer and JSON response, it wanted 500000 for gas. It would be great if the UI could present the error in a better way and make the information more explicit about why the transaction failed.

Like an error message that says "Not enough gas to execute contract. Gas used: 282988. Gas wanted: 500000."

**JSON response:**

{"tx":{"type":"cosmos-sdk/StdTx","value":{"fee":{"gas":"500000","amount":[{"denom":"uscrt","amount":"125000"}]},"msg":[{"type":"wasm/MsgExecuteContract","value":{"msg":"eM+4gotmHo6+Xtggm0yGJRi/sOn+clNL0F4xBQFEWh8e8P0AX6gyxL6cw8MfMOLDh5FmtolVqhOmHO1wuyLLB0ZkN5JYlS7zW99/5/JpKWNtX/YcVUqP0lYvE3ZM2s4lknpy1wNB3YKpIrQ3vW2c6w82C13L1GPxKCdfBuczsa348s7X9eWwtLE4h1wlPai0Rqr1KCBe95Z4qdeclgKcTKQR7VJQ8+e0WlDgTtzcXo8FS9iTBtCdnWLY54SXtAEmH+FFnFAIN9GjSul+xyUgKvlwIxy4mg7RqZTkzm9q87nI/8Ep4oKbhMYYuHvy/cbrgBukFDzlyzVScFsSAoRSZTfOdWTqVEmTnhxOTafZq+0HLrpGJ02+N7jXO36aCXCAjC92EUD6cEgSGG3NpCyLsdd1cpTCYZIr+/Vy/3SkpgmatttzDWYD2kGUyb2pb+RsPXQ4p7hseceCv2HSkA+OMyR1NvthsqUsyMbDRQi2S8w+Po6gMmFtvsVvuKerziBOAeUj8qgnzdh2bQWl5k2b38bTlqGFkmj/a3nNjb4GzB3rBpWf8p4vl7KzxsijnlUd4p6CgfFm99nQ51tFyj9lAafHBPmdXXetLguQczAcCKEiE8oazmjKNeT3olYiWVI/2yPzxZWgniXI9WGeqF5CQxeh9Z6HNhZAMjtLtX4GVA0rIwr+l6JN3NNhRPtmHlmc4jIgLtGP72XwMZBtUFxrZqN+kJxJ7AkshAh92PxldZMaz8LPMfdw65kRGcmUH74FzN3xuMwACSNfieRMGPMQ","sender":"secret10j7agvhygt68f5hjg349u6vy5662c9egs6djuh","contract":"secret1uakhxh3qwe2k8khww709cpxlm8kmwapufmfrr0","sent_funds":[],"callback_sig":null,"callback_code_hash":""}}],"memo":"","signatures":[{"pub_key":{"type":"tendermint/PubKeySecp256k1","value":"A8reihAk3CKjhCbDnKbTbXb6It8gVwVKDuQ5GJrttF1C"},"signature":"pfcWb3SFcs6WfJBji7ymFGnANgtGgEi7lemS0QfS2whbqwj6Qy2/8fuTWrgmvs+QxbG1eKqNhV/AHC5+4Rubqg=="}]}},"code":3,"height":"2680295","txhash":"FB1535F0FAC8A6D4B9C96A55DD28B4DE7E72ADA52B6452025C42700A6FA7F094","raw_log":"execute contract failed: encrypted: bRjhWWLBhOgs7qfDYNR3Ddp+rqhqG6VYT/HUN2gCkvXZFQ8RuILlwDi8xaXNWjJB9SYC2MHWh7yBWFsppWOFslPGLP9qlSuvvyJA1HEOpc45kfxVTF4nYTbStNgkhIgM9w==: failed to execute message; message index: 0","gas_used":"282988","codespace":"compute","timestamp":"2021-03-20T20:20:04Z","gas_wanted":"500000"}

**Comment by Cashmaney** [comment]
This should be mostly fixed - will reopen if it keeps happening
