### ISSUE TITLE
ERC20 smart contract interaction allowance - contract UX improvement

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#12]
Currently every time Alice wants to swap ERC20 to secretERC20, she needs to first approve the bridge deposit contract to spend up to a limit and then sign the actual transaction

In all smart contract interactions, Alice would initiatlize the bridge deposit contract once to allow the contract to spend up to X ERC20 and then every following TX would just need Alice's signature. This way we reduce required steps from 2 to 1.

Here's an example:
First time trading BAL (ERC20) on Balancer. Unlock = authorize
![image](https://user-images.githubusercontent.com/15679491/101111986-5f07ef00-35aa-11eb-8548-b27673fb1aff.png)

Metamask signing screen
![image](https://user-images.githubusercontent.com/15679491/101112012-6c24de00-35aa-11eb-9af8-2178675426a8.png)

Advanced view where you can set the spending limit
![image](https://user-images.githubusercontent.com/15679491/101112024-721abf00-35aa-11eb-8b3f-b66c93519f8b.png)

**Comment by assafmo** [comment]
Okay. Is this common practice in Ethereum apps?

**Comment by cankisagun** [comment]
Yes this is standard practice. If you want to play with an ETH contract, I can send you ETH :)

**Comment by assafmo** [comment]
No need, I believe you :)

**Comment by cankisagun** [comment]
Actually I tried manually increasing the limit in the first TX and then tried another tx where I was below the threshold. It still asked me for 2 TXs (one allowance + 1 actual tx)
![Uploading image.png…]()

**Comment by assafmo** [comment]
@cankisagun the erc20 contract must support "unlimited" allowance, otherwise it looks like this:
![image](https://user-images.githubusercontent.com/22766533/102015105-34fcbc80-3d62-11eb-9201-68e08d33a3f1.png)

Not sure how they are doing it.

**Comment by assafmo** [comment]
Done 79f09843118de24faa56b69f4123281469c4038f
