### ISSUE TITLE
My transactions, in transactions tab don't work, need fixing or removing

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/EthereumBridgeFrontend#13]

**Comment by assafmo** [comment]
@cankisagun I don't follow, can you elaborate?

**Comment by cankisagun** [comment]
Refering to this tab
![image](https://user-images.githubusercontent.com/15679491/101405299-ddfc7080-38a5-11eb-8f9e-1c2a03f2ad8f.png)

When I click only my transactions I get this link (https://ethbridge.test.enigma.co/explorer) and a blank page

**Comment by assafmo** [comment]
Removed it, it was too broken to fix. Maybe down the road. :stuck_out_tongue:
