### ISSUE TITLE
UI improvements for bridge farming

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#14]
We need to make 3 main improvements to the current UI in order to clearly communicate rewards.

1) Information page to navigate all bridge rewards
2) Ability for users to immediately stake their secretETH (secretERC20s) to the staking contract - nice to have
3) Page for user to see / claim SCRT rewards _(I need more info on how this will work in order to provide meaningful comments WIP)_  _- dashboard is nice to have, claiming is addressed in 1_

**Information page to navigate bridge rewards**
This should be a list of: 
- supported assets, 
- amount of TVL in the bridge (for each asset) 
- APY for each asset
- available assets of Alice (if there's a metamask connection) - _lower priority_

We can show ETH on top and make the list sortable by TVL & APY (if possible, if not just TVL is fine). If we do the same rewards for all ERC20s the APY will be identical but we'll have TVL in different values.  Assuming user has connected to Metamask, we can also show how much a user can deposit (check out YFI vault screenshot)
Clicking on the asset would take the user to the "Bridge Tab" with that asset already selected for the swap.

_We can change the current assets tab to include these details. Here are some examples from projects on how they communicate different pools and rewards involved in each pool_:

_YFI_ - YFL shows users available balance unlike CRV + Sushi, which I believe is helpful
![image](https://user-images.githubusercontent.com/15679491/101419993-4b68cb00-38bf-11eb-871b-8e53e55ea9ff.png)

_[CRV](https://www.curve.fi/) -single asset, no impermanent loss_: You'll see that clicking on the pool takes you to the screen where you can swap + provide liquidity
![image](https://user-images.githubusercontent.com/15679491/101419643-71da3680-38be-11eb-9411-4854c85b0331.png)

_[Sushi swap](https://sushiswap.fi/home)_ You'll see that clicking on the icon (left side), takes you to the screen where you can swap + provide liquidity
![image](https://user-images.githubusercontent.com/15679491/101419749-abab3d00-38be-11eb-8e55-fed35a15d4f5.png)

_Will be doing a bit more research but I think this is what we want to communicate to the users. If we want to get design UX help, let's discuss_

**Ability for users to directly stake their secertETH / secretERC20 for rewards**
We require a UX, where Alice first needs to mint secretETH and then provide that to a secret contract to be eligible for rewards. Best in-class examples in this UX gives users 2 options: i) just to mint secretETH and ii) mintsecretETH and deposit it in a single click (then multiple metamask clicks).

_For example, SushiSwap has the following UX_
Alice adds liquidity and get Sushi tokens. She can then stake those Sushi tokens for platform revenues
![image](https://user-images.githubusercontent.com/15679491/101421741-09da1f00-38c3-11eb-882b-265025a42ec3.png)
![image](https://user-images.githubusercontent.com/15679491/101422052-be744080-38c3-11eb-9ca5-4d5e474f272d.png)
The second step may be a friction that prevents Alice from staking and earning Sushi rewards

Whereas in_[Curve](https://www.curve.fi/3pool/deposit)_ (even though the UI is horrible), when you choose deposit for a pool, you have 2 options: 1) deposit, 2) deposit and stake. I think we can offer the 2 options to ensure everyone enjoys SCRT rewards
![image](https://user-images.githubusercontent.com/15679491/101422006-a3093580-38c3-11eb-9d10-8025056347c0.png)

We can modify the "Bridge Tab" to have 2 horizontal confirming buttons instead of the current continue:
1) get secretETH
2) get secretETH + yield
![image](https://user-images.githubusercontent.com/15679491/101422450-b8329400-38c4-11eb-9beb-39a589db739f.png)

**Dashboard - Page for user to see / claim SCRT rewards**
We require a new tab called "Dashboard", **where Alice can see her rewards**:
- Alice's TVL locked in the bridge (I think USD amounts would be good)
- Amount of secretSCRT rewards Alice has won + can claim in a given time
- A list that shows all bridge staking rewards pools Alice is a part of. So one line for each staking contract (secretETH, secretLINK, etc.) showing total pool size (denominated in ETH/LINK), Alice's share (%) and Alice's rewards (secretSCRT). Ideally the secretSCRT rewards amount should add up to the bullet above.

**For claiming rewards**, I understand that rewards are distributed to Alice, when Alice either increases or reduces her staked secretETH or secretERC20. If possible we should give Alice the option to claim her most update rewards from each pool that's listed (3rd bullet in this section) so she can do it for each pool. _I am guessing Alice can also ask the contract to collect the rewards w/o increasing or decreasing her staked amount_  cc @toml01 

Here are two examples that I find very clean and intuitive:
_YFI dashboard page_
![image](https://user-images.githubusercontent.com/15679491/101818249-99651500-3af1-11eb-952b-3f857dd0d662.png)

_Balancer dashboard page_
![image](https://user-images.githubusercontent.com/15679491/101818346-b4d02000-3af1-11eb-856f-1305c7a8690d.png)

_Compound balance claim_
![image](https://user-images.githubusercontent.com/15679491/101819185-e0073f00-3af2-11eb-8699-7f8d80db81e1.png)

**Comment by cankisagun** [comment]
**Information page to navigate all bridge rewards to-do's**

It would be nice to add some notification for the user that she has funds staked in a reward pool. Currently it's not possible to see this, unless you expand the view:
![image](https://user-images.githubusercontent.com/15679491/103691894-f7f0a800-4f64-11eb-90d0-a30a3ae1474d.png)
![image](https://user-images.githubusercontent.com/15679491/103691913-017a1000-4f65-11eb-8a4f-faff4a92c333.png)

Possible approaches to this can be:
- Show the staked amount like yearn.finance
![image](https://user-images.githubusercontent.com/15679491/103691976-19519400-4f65-11eb-8a35-be7f8f621c79.png)
- Use color coding (or darker borders) to highlight pools with staked funds

**Comment by Cashmaney** [comment]
Done. Closing this for now - we can open new issues for more specific stuff
