### ISSUE TITLE
Error bar when cancelling a Keplr TX

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#162]
I get this empty bar where I should be shown an error
![image](https://user-images.githubusercontent.com/15679491/116313718-f68cfa80-a762-11eb-8d00-5e93ac6f0f7b.png)

Let's fix this to display an error msg.
![image](https://user-images.githubusercontent.com/15679491/116313800-17555000-a763-11eb-87d3-9488aac3ca79.png)

**Comment by alejandrordzl** [comment]
I see, It should be fixed with the last commit.

**Comment by cankisagun** [comment]
yep - closing this issue
