### ISSUE TITLE
NEEDED FOR LAUNCH - Update the FAQ / Info tab

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#17]
There are currently links to Harmony, we must update this before the launch

The text can be found here
https://docs.google.com/document/d/1ujToFJJBlZ5kOQcHkAnys4ekvplDTh8SXBJ3h8-izJ8/edit

**Comment by assafmo** [comment]
Done 33ffd38b100ee5f1b6c943b85496539d320fc72c
