### ISSUE TITLE
NEEDED FOR LAUNCH - Min TX amount for Secret Network -> Ethereum (both UI and possibly contract)

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#18]
Currently I can sign a TX that allows movement of funds from Secret Network to Ethereum that is lower than fees to be paid on ethereum. See below:
![image](https://user-images.githubusercontent.com/15679491/101960755-14076080-3bd6-11eb-8dd2-88c6d512123c.png)

Not sure if it's taking long b/c it's rejected and we don't have an error for it or if it's not going to ever go thru.
![image](https://user-images.githubusercontent.com/15679491/101961048-e242c980-3bd6-11eb-8de6-851b616ac6d2.png)

If this is not an easy fix (to set the min. tx amount as a variable based on eth gas price and secretToken/ETH conversion), maybe we should set the min amount to $10 or 0.025ETH equivalent

**Comment by cankisagun** [comment]
Also got this after a long while - maybe we need to change the error text here to something like:
"Please make sure the amount you are transferring over the bridge is greater than the swap fee"

**Comment by Cashmaney** [comment]
Depending on gas price, fees will be anything from 5-25 USD (if defi goes crazy it can also go up to 100+), so we'll probably set it to ~50USD at first, and set a variable minimum later

**Comment by cankisagun** [comment]
I think max of 100 gas price should be safe

**Comment by assafmo** [comment]
https://github.com/enigmampc/EthereumBridgeFrontend/commit/69b0365cb45c397681e3bac199859aeb8d8f538b
