### ISSUE TITLE
Keplr viewing key issues - this now works FYI

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#20]
Report Keplr issues here.

There's this issue with viewing keys. I have viewing keys working for my browser extension but not for the UI. Check out this screenshot
![image](https://user-images.githubusercontent.com/15679491/102141152-604cdd80-3e2e-11eb-954d-8d4f962bdd9a.png)

**The real problem is when I'm trying to go back to Ethereum, b/c the UI can't verify my viewing key, it thinks I have 0 secretETH and cannot do back to Ethereum**

![image](https://user-images.githubusercontent.com/15679491/102143078-67291f80-3e31-11eb-92a9-5f220ff497dd.png)

When I try to recreate the viewing key, I can't hit submit after the key is generated
![image](https://user-images.githubusercontent.com/15679491/102143788-7f4d6e80-3e32-11eb-8b3c-f7fe21945bd8.png)

**Comment by cankisagun** [comment]
Viewing key problems continue with secretUNI - can't submit the viewing key on keplr
![image](https://user-images.githubusercontent.com/15679491/102146454-f38a1100-3e36-11eb-8b0c-193c2bad681b.png)

**Comment by cankisagun** [comment]
I left the computer for an hour and now I'm able to submit the tx for the viewing key and things work well. This may have been a bug with Keplr. Thou the interactions are very slow on Keplr and there's no good user feedback, something that prepares you to wait
![Uploading image.png…]()

**Comment by assafmo** [comment]
Does it work after a refresh?
