### ISSUE TITLE
Keplr extension issue

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#21]
Already reaised in Keplr TG. Just for consistency

moved some eth-> secretETH and tried to send it in SN using keplr extension. I got the following error both for high and average gas selected
![image](https://user-images.githubusercontent.com/15679491/102142768-f124b880-3e30-11eb-96d0-1e53eff75bbc.png)

**Comment by assafmo** [comment]
@cankisagun is this still an issue?

**Comment by cankisagun** [comment]
probably not closing
