### ISSUE TITLE
CSHBK Rewards Not Dispensing

### ISSUE THREAD

**Issue by ESWood** [scrtlabs/EthereumBridgeFrontend#225]
![Screenshot from 2021-06-28 22-24-38](https://user-images.githubusercontent.com/83804269/123733235-be885d80-d860-11eb-8e8e-affcf12d5495.png)

Expected behavior: CSHBK Rewarded for swaps on eligible pairs
Actual behavior: Message notified of CSHBK received on swap page but no CSHBK received in wallet

Issue reported by several users, tested to confirm, screenshotted results included with this issue.

**Comment by ESWood** [comment]
Issue is affecting **_all_** eligible pairs.

**Comment by toml01** [comment]
We found the problem, fixing right now. It's an issue with the configuration update in the [AMM factory contract](https://github.com/enigmampc/SecretSwap/blob/master/contracts/secretswap_factory/src/contract.rs#L133)
