### ISSUE TITLE
Earn: staked balance hangs on "Fetching Balance..." forever for 6 assets

### ISSUE THREAD

**Issue by AronVanAmmers** [scrtlabs/EthereumBridgeFrontend#229]
On the [Earn](https://bridge.scrt.network/earn) page, for 6 specific assets (DAI, WBTC, LINK, OCEAN, RSR, THORChain), the staked balance shows "Fetching Balance..." forever. The button **View Balance / Available Rewards** never appears, hence the user can never create a viewing key, can't see their staked tokens, and can't withdraw them.

Expected situation, e.g. USDT, button **View Balance / Available Rewards** is visible:

![2021-08-17 12_04_14-𝕊ecret Bridge - Brave](https://user-images.githubusercontent.com/1123543/129707515-c5cdfd17-851e-4a2a-952c-cdb7b21f8627.png)

Actual situation for DAI, WBTC, LINK, OCEAN, RSR, THORChain:

![2021-08-17 12_04_25-𝕊ecret Bridge - Brave](https://user-images.githubusercontent.com/1123543/129707616-2d099c89-dc37-431a-a410-423811e2c0cf.png)

Reproduced on latest Brave / Windows, Brave / Linux, Chrome / Linux, all with latest Keplr Wallet (0.8.13). On each, this happens with the same 6 assets.

Tested with a freshly generated seed / address on Keplr Wallet, and freshly installed Keplr Wallet, i.e. this is not caused by previous state of the Keplr extension / SCRT account / browser / OS.

**Comment by AronVanAmmers** [comment]
Full page screenshot, showing how the button **View Balance / Available Rewards** correctly appears for most assets, but for DAI, WBTC, LINK, OCEAN, RSR, THORChain remains at "Fetching Balance..."

![image](https://user-images.githubusercontent.com/1123543/129708131-da0f8b34-99fd-4c9a-a480-dd9919f752f6.png)

**Comment by AronVanAmmers** [comment]
Tested with an older version of Keplr Wallet (v0.8.6, from 21 April 2021). No changes. So likely not related to any recent changes in Keplr.

**Comment by Cashmaney** [comment]
Fixed, thanks for reporting @AronVanAmmers!

**Comment by AronVanAmmers** [comment]
Thanks! Confirmed working on my end.
