### ISSUE TITLE
Default Gas limits too low for ETH transactions

### ISSUE THREAD

**Issue by KurogeWashu** [scrtlabs/EthereumBridgeFrontend#27]
Gas limit defaults to 50,000 for ERC20 approve transactions. Can see multiple transactions failing https://etherscan.io/address/0xf4b00c937b4ec4bb5ac051c3c719036c668a31ec

_Originally posted by @KurogeWashu in https://github.com/enigmampc/EthereumBridgeFrontend/issues/9#issuecomment-748558983_

**Comment by assafmo** [comment]
Updated to 75k, should be working now. Thanks @KurogeWashu for reporting! :heart:
