### ISSUE TITLE
Add disclaimer to earn page

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#32]
Add a disclaimer on the top of the page to instruct users to refresh the page if they can't see their balances. 

Disclaimer text:
If you have created viewing keys for secretTokens and secretSCRT, you should be able to see secretTokens locked in the rewards contract and your rewards. If you can't see these figures please refresh your browser.

Text can be placed right above ETH pool earn box
![image](https://user-images.githubusercontent.com/15679491/104387563-673a3f00-5505-11eb-8894-d64a178bafcf.png)
or
![image](https://user-images.githubusercontent.com/15679491/104388048-67870a00-5506-11eb-8115-11028c703057.png)

**Comment by cankisagun** [comment]
I would also add welcome message similar to the one you see when you land the bridge. 
Text would include

**Improve privacy guarantees and earn SCRT rewards**
The higher the number of addresses and amount of funds interacting with the bridge, the higher the anonymity guarantees of the bridge. _Let's earn yield and protect our privacy!_

1) In order to earn rewards, users must deposit secretTokens to a rewards contract by choosing Earn
_Note: If you have created a secretToken, please make sure you have already created the viewing key to see your balances. You can always create a viewing key by clicking on lock icon_

2) Once users deposit secretTokens to the rewards contracts, they will start to accumulate bridge rewards in secretSCRT. In order to view your rewards balance and your deposited secret tokens make sure you have created a viewing key for each reward pool.

3) When users withdraw or deposit secretTokens from/to rewards contract, the bridge rewards they have accumulated will be automatically transferred to their wallet (Keplr)

4) Users can use Keplr app to convert secretSCRT (privacy token) to SCRT (Secret Network native coin) using [Keplr app](https://wallet.keplr.app/#/secret-2/secret-secret) to participate in staking.


This would be shown once to each user coming to Earn tab

**Comment by cankisagun** [comment]
Make icon as well as the `unlock tokens` (now `view balance`) text clickable

Unlock above the withdraw bar doesn't work. Let's link that to creating a rewards contract viewing key as well

**Comment by Cashmaney** [comment]
@walter-lkmx @cankisagun commenting here as well - 

We reverted the changes.

The footer changes affect the modal text as well, which looks a bit odd, and hides the "Got it" button, so it cannot be closed.

The earn modal overwrites the general info modal and appears on the main page
