### ISSUE TITLE
Transactions link to puzzle.report instead of secretnodes.com

### ISSUE THREAD

**Issue by PrivatePixels** [scrtlabs/EthereumBridgeFrontend#42]
We just changed the domain of our explorer from puzzle.report to secretnodes.com. Everything else is the same about url structure.

This occurs on the following page.
https://bridge.scrt.network/explorer

Would appreciate it if you updated this :)

**Comment by cankisagun** [comment]
@moonstash can you pls send a PR?

**Comment by PrivatePixels** [comment]
@cankisagun sure thing :)

**Comment by PrivatePixels** [comment]
@cankisagun so I don't actually know how to make this change, i submitted a few pr's but none of them actually fixed this. So I wanted to reach out to let you know we are going to be making a change to how the redirect works to force people to the secretnodes.com homepage when they visit any url like puzzle.report/* . We don't want people confused by the puzzle.report url. If someone could figure out how to make the requested change that would be great :)

**Comment by PrivatePixels** [comment]
ok this change has been made. As of now anyone who visits puzzle.report or puzzle.report/* will be forced to the secretnodes.com homepage.

If the update is made for the bridge to use secretnodes.com then everything should work fine again.

update assaf fixed this. Thanks Assaf!
