### ISSUE TITLE
Creating viewing keys for all assets each time we open the UI is a poor experience

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/EthereumBridgeFrontend#5]

**Comment by assafmo** [comment]
Fixed by 74820b087b9e806732990ec3f579a6787fae2305

**Comment by cankisagun** [comment]
I am getting this error on Keplr (after I removed the network and added again) when I click on unlock secretETH 
![image](https://user-images.githubusercontent.com/15679491/101417494-c6c77e00-38b9-11eb-9903-a2232f6c62b5.png)

Keplr screenshot
![image](https://user-images.githubusercontent.com/15679491/101417544-e1015c00-38b9-11eb-95d7-48d6ee28ed40.png)

**Comment by cankisagun** [comment]
Assaf see this bug / issue

**Comment by assafmo** [comment]
I think this is fixed, please confirm?

**Comment by cankisagun** [comment]
Wallet issue is fixed, now I can create viewing key for secretETH.

I have this denomination problem thou - I never had 100 secretETH 
![image](https://user-images.githubusercontent.com/15679491/101521902-705b4d80-3954-11eb-9bdd-175e08f378e7.png)

**Comment by assafmo** [comment]
This is ok. Only a testnet issue.

**Comment by assafmo** [comment]
On testnet we have `secretETH` with 15 decimals instead of 18. It will be 18 on mainnet.
