### ISSUE TITLE
Bridge main page wallet representations

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#52]
Current representation of wallet addresses and balances on the right is very clunky. I suggest we upgrade the current design. The fields captures are ETH balance, wallet address (not necessary to be fully visible on the main page), and ERC20 balance if selected
![image](https://user-images.githubusercontent.com/15679491/105434331-5a1a0000-5c29-11eb-86c3-ff44bc4f2921.png)

Here are some ideas about wallet design:
Uniswap
We can just add a box for ETH and wallet address like shown here. The ERC20 can be shown as described in issue #53
![image](https://user-images.githubusercontent.com/15679491/105434385-79189200-5c29-11eb-9742-9fb097b1b5aa.png)

Mirror
![image](https://user-images.githubusercontent.com/15679491/105434527-baa93d00-5c29-11eb-83cf-aa4c5f86e33d.png)
We can use this method to show just the secret wallet last digits + secret balance

Looking at issue #53, we will only need SCRT balance in the mainpage

**Comment by cankisagun** [comment]
Show metamask address and ETH balance
Show keplr address and SCRT balance

Both on the top right corner similar to mirror and uniswap

**Comment by walter-lkmx** [comment]
![image](https://user-images.githubusercontent.com/20671223/107681023-68b96d00-6c53-11eb-919e-96e1050c3d8d.png)

**Comment by cankisagun** [comment]
@walter-lkmx design looks great - are you planning to code this (react.js) or will you pass us the components?

**Comment by walter-lkmx** [comment]
React development required
