### ISSUE TITLE
Bridge main page balance representation

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#53]
Currently balances for ETH / ERC20 / Secret and SNIP20s are shown both below the amount text box and on the right side
![image](https://user-images.githubusercontent.com/15679491/105435054-a3b71a80-5c2a-11eb-8470-3236768e7f04.png)

There can be a more compact way of showing these balances right above the box to enter how much use in the bridge
![image](https://user-images.githubusercontent.com/15679491/105435568-93536f80-5c2b-11eb-9b87-112cb32a4c51.png)

In Secret -> ETH section, we can keep min transaction amounts below the text box as is

One idea of a design is
![image](https://user-images.githubusercontent.com/15679491/105437038-52a92580-5c2e-11eb-8ff4-347f9667a77d.png)

**Comment by cankisagun** [comment]
Next step: Look at Figma designs to finalize the design for this cc @walter-lkmx

**Comment by walter-lkmx** [comment]
UPDATE
The Figma file has been updated with the latest feedback, @cankisagun, let us know your thoughts.

> Next step: Look at Figma designs to finalize the design for this cc @walter-lkmx

@cankisagun Here is the Figma where we are working on, of course, this is WIP, but feel free to take a look and lets us know your thoughts. 

[Figma - Secret Bridge](https://www.figma.com/file/jv3Q9OmhPj6FUhkkb2oIKU/SecretBridge?node-id=70%3A195)

![image](https://user-images.githubusercontent.com/20671223/107680652-fd6f9b00-6c52-11eb-95ff-92293fa7d6dd.png)

**Comment by walter-lkmx** [comment]
React development required
