### ISSUE TITLE
Bridge page asset selection

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#54]
Currently Alice can choose ETH or ERC20s from the scroll down menu. We can combine these two views and just have a simple dropdown menu like Uniswap does

Current:
![image](https://user-images.githubusercontent.com/15679491/105435425-55eee200-5c2b-11eb-93bd-8c030249c808.png)

Ideas:
Uniswap
![image](https://user-images.githubusercontent.com/15679491/105435463-669f5800-5c2b-11eb-8434-8dfdd90ea049.png)
![image](https://user-images.githubusercontent.com/15679491/105435481-6dc66600-5c2b-11eb-94cd-2e785a3fa243.png)

Current dropdown menu is already has the search function embedded maybe there's a better way to show that

**Comment by cankisagun** [comment]
Next step: Try to port uniswap design here. The logic is setup in secret auction which is written in vue.js
Embed figma to bridge design. After that we'll implement this in react.js

**Comment by walter-lkmx** [comment]
![image](https://user-images.githubusercontent.com/20671223/107681168-930b2a80-6c53-11eb-83f5-da79ac8ad43a.png)

**Comment by walter-lkmx** [comment]
React development required

**Comment by cankisagun** [comment]
Look under bridge section in figmas https://www.figma.com/file/jv3Q9OmhPj6FUhkkb2oIKU/SecretBridge?node-id=70%3A2478
