### ISSUE TITLE
finance.scrt.network landing page

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#56]
We should have a landing page that allows users to access different secret defi products. A good design example for this is yearn.finance v1
![image](https://user-images.githubusercontent.com/15679491/105521597-1f0be100-5caa-11eb-9d2e-fe0239d936ed.png)

We can have the following columns for now
- SCRT: Navigate different use-cases for SCRT in Secret Network (we can add secret logo) (no link at the moment)
- Bridge: Bridge enables minting of Ethereum assets as secretTokens (privacy tokens) on Secret Network (link to bridge.scrt.network)
- SecretSwap: Front-running resistant AMM for secretTokens (no link at the moment)
- OTC: Sealed bid auctions for large quantity off-order book trading for secretTokens (link to auction UI when done)
- Earn: Explore yield opportunities in Secret Network (no link at the moment)

**Comment by cankisagun** [comment]
Next step: create figma views

**Comment by walter-lkmx** [comment]
@cankisagun Here is an initial representation, let us know your thoughts:

[Figma](https://www.figma.com/file/jv3Q9OmhPj6FUhkkb2oIKU/SecretBridge?node-id=146%3A941)

![image](https://user-images.githubusercontent.com/20671223/107682000-a5399880-6c54-11eb-8073-0d0ffa622740.png)

![image](https://user-images.githubusercontent.com/20671223/107682050-b387b480-6c54-11eb-92ac-4d61dc217f4e.png)

**Comment by cankisagun** [comment]
these look great I left some comments also shared it with the team to collect some feedback. Is the next step to give greenlight for development?

**Comment by cankisagun** [comment]
Final list of improvements @walter-lkmx 
- Tab on top (Assets etc.) should be removed
- Defi products title should be removed
- under bridge -> change `Private Tokens` withs `privacy tokens`
- get secretSwap logo from Sandy / Tor
- let's make the whole card clickable not just the arrow
![image](https://user-images.githubusercontent.com/15679491/108910408-ceaed880-75f3-11eb-80f5-342d5e100ffa.png)
- let's add secretswap link to the secretSwap card -> https://bridge.scrt.network/swap
- let's add earn link to earn -> https://bridge.scrt.network/earn
- let's add shade (greyish) to SCRT b/c it's not clickable atm

**Comment by cankisagun** [comment]
once this is done, I would like to test everything in a local environment
