### ISSUE TITLE
UI inconsistency for balances

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#6]
wip
![image](https://user-images.githubusercontent.com/15679491/100907963-efeea580-3498-11eb-934e-2b8bd412d216.png)

updates on balances happen slowly with a lag

there's no Icon for TUSD

**Comment by assafmo** [comment]
That's probably because of weird delays Harmony were using. Did it never update to 3 TUSD?

**Comment by cankisagun** [comment]
I think it does after a delay

**Comment by cankisagun** [comment]
also check this out
![image](https://user-images.githubusercontent.com/15679491/101086470-e5a6d700-357e-11eb-8bb8-28f2f1d4b27a.png)

**Comment by cankisagun** [comment]
also
![image](https://user-images.githubusercontent.com/15679491/101086669-33bbda80-357f-11eb-9852-1f2b3830a1f2.png)

**Comment by assafmo** [comment]
Behind the scenes it's pretty messed up (the balances inconsistencies), not sure it's worth the time right now.

**Comment by assafmo** [comment]
And the secretETH inconsistency is testnet behavior only (ahm ahm @Cashmaney)
