### ISSUE TITLE
Visualization for ERC20 allowance required from ETH -> SCRT

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#64]
Users are required to sign a TX that allows bridge to spend ERC20s on their behalf. This is a one time thing. 

Currently we have this notification to alert the users:
![image](https://user-images.githubusercontent.com/15679491/106052918-2b33dc00-60b8-11eb-9f91-5d3b53dd9a23.png)
when you click continue
![image](https://user-images.githubusercontent.com/15679491/106052944-34bd4400-60b8-11eb-9d08-1c86264f0a22.png)
Then user clicks continue and either are 2 TXs (first time using the ERC20 on the bridge) or a single TX

I propose we add this design that I saw in Uniswap instead
_If using the asset for the first time_
![image](https://user-images.githubusercontent.com/15679491/106053095-60d8c500-60b8-11eb-9a54-f42b2fd047e4.png)
_If asset was used before_
![image](https://user-images.githubusercontent.com/15679491/106053123-6cc48700-60b8-11eb-9177-d2857b4f410f.png)

We can also kill the `back` button b/c you can click anywhere to go back

**Comment by walter-lkmx** [comment]
[Figma File](https://www.figma.com/file/jv3Q9OmhPj6FUhkkb2oIKU/SecretBridge?node-id=202%3A7667)
![image](https://user-images.githubusercontent.com/20671223/107806182-5571d480-6d1b-11eb-8f0e-0e3dd9de5648.png)

**Comment by walter-lkmx** [comment]
React development required
