### ISSUE TITLE
Keplr wallet placement

### ISSUE THREAD

**Issue by cankisagun** [scrtlabs/EthereumBridgeFrontend#73]
Let's get Keplr logo in the same line with FAQ and other tabs
![image](https://user-images.githubusercontent.com/15679491/107991160-07bbcd00-6fa4-11eb-8319-94669c037432.png)

This is how wallets are shown in other dapps
![image](https://user-images.githubusercontent.com/15679491/107991198-17d3ac80-6fa4-11eb-80a7-0d4a05c6292f.png)

**Comment by assafmo** [comment]
This is not that easy. The bridge's wallet and the swap's wallet are completely separated.

**Comment by cankisagun** [comment]
I'm talking about moving the logo up to the same line with the FAQ - if it's hard let's drop it

**Comment by assafmo** [comment]
This isn't hard, but I tried it and it looked worse. :-)
