### ISSUE TITLE
Long waiting times for view-keys to load.

### ISSUE THREAD

**Issue by mohammedpatla** [scrtlabs/EthereumBridgeFrontend#86]
Not sure if this is Keplr related or front-end related, but the view-keys take close to 30s-2min just to load, and show my balance.
So if I refresh the page, takes a lot of time to view my coins.

Maybe storing the view-keys in local storage, that expires daily?

**Comment by uxt-exe** [comment]
I have issues with loading balances taking a while, too. It looks like the `https://secret-api.azurewebsites.net/secret-2/lcd/wasm/contract/<secret address>/query/<hex query>` endpoint doesn't respond very fast, usually 500ms but can take up to two seconds. That wouldn't be so bad but this query is performed for each possible SNIP20, and it doesn't appear to be parallel on first load, so it adds up.

**Comment by mohammedpatla** [comment]
Yea i think the new update has drastically changed that.

**Comment by assafmo** [comment]
We saw a huge traffic spike at launch, and our node provider couldn't handle the amount of balance queries. Thousands of users, each querying their balances for all tokens, LPs and pool sizes.
We're still working on optimizations and increasing our bandwidth. It's not related to Keplr.

Thanks for the issue.  !
