### ISSUE TITLE
Set a lower gas limit for Ethereum txs

### ISSUE THREAD

**Issue by assafmo** [scrtlabs/EthereumBridgeFrontend#9]

**Comment by KurogeWashu** [comment]
Gas limit defaults to 50,000 for all transactions. Can see multiple transactions failing.

**Comment by assafmo** [comment]
@KurogeWashu It's limited to 75k

**Comment by Cashmaney** [comment]
Also, if there are any transactions that fail please link them so we can take a look

**Comment by assafmo** [comment]
@Cashmaney I took care of it, it was an `.env` mismatch on production, my bad :face_with_head_bandage:
