### ISSUE TITLE
Prevent loss of funds through accidental single-side liquidity add.

### ISSUE THREAD

**Issue by uxt-exe** [scrtlabs/EthereumBridgeFrontend#94]
As per the [Uniswap docs](https://uniswap.org/docs/v2/smart-contract-integration/providing-liquidity/) (thanks baedrik), it is possible for someone to add liquidity that is not at the current swap rate, leading to diminished LP return and a shift in the price. If one side is zero, the price shift will occur but no LP tokens will be issued.

I believe we have inherited this design attribute in the Secret AMM, and under certain conditions the UI does not prevent a user from performing bad liquidity adds. 

Typically the UI prevents a user mistakenly adding single side liquidity by disabling the add button. Here you can see the button is greyed out and asks the user to enter an amount. 
![bug1](https://user-images.githubusercontent.com/60639498/108495144-45974a80-725d-11eb-9138-ddf4cc03d9ed.png)

However, a user can enter zero if they are confused and enter a state where it's possible to send the funds off and get nothing in return. Publishing this will yield no LP tokens.

![bug2](https://user-images.githubusercontent.com/60639498/108495445-a6bf1e00-725d-11eb-8965-1d186b267fdb.png)

From reports in the `#amm-support` channel it sounds like there are at least two cases where this has occurred already. Ideally we'd check that both sides were close to expected, given the price, but a simple check that both fields are at least greater than zero would be useful too.

**Comment by assafmo** [comment]
Thanks for the detailed issue! This is now fixed, and we're still running back-checks to figure out whether this actually happened.
